services:
  outline:
    env_file:
      - stack.env
    image: docker.getoutline.com/outlinewiki/outline:0.78.0
    ports:
      - ${HTTP_PORT_MAP}
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
  redis:
    env_file:
      - stack.env
    image: redis
    ports:
      - ${REDIS_PORT_MAP}
    volumes:
      - redis-data:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
  postgres:
    env_file:
      - stack.env
    image: postgres
    ports:
      - ${POSTGRES_PORT_MAP}
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  redis-data:
  storage-data:
  database-data: